development:
  adapter: postgresql
  database: enquesta_development
  host: localhost

test:
  adapter: postgresql
  database: enquesta_test
  host: localhost

production:
  adapter: postgresql
  database: enquesta_production
  host: localhost